/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdkhooks>
#include <sdktools>
#include <sdktools_functions>
new g_iVelocity ;
new Handle:l4d_tank_throw_si;
new Handle:l4d_tank_throw_hunter 	;
new Handle:l4d_tank_throw_smoker 	;
new Handle:l4d_tank_throw_boomer 	;
new Handle:l4d_tank_throw_charger 	;
new Handle:l4d_tank_throw_spitter	;
new Handle:l4d_tank_throw_jockey		;
new Handle:l4d_tank_throw_tank		;
new Handle:l4d_tank_throw_self
new Handle:l4d_tank_throw_tankhealth		;
new rock[MAXPLAYERS+1];
new tank=0;
new L4D2Version;
public Plugin:myinfo = 
{
	name = "tank's throw special infected",
	author = "Pan Xiaohai",
	description = "tank's throw special infected",
	version = "1.0",
	url = "<- URL ->"
}
new bool:gamestart=false;
new Float:throw_all[8];
public OnPluginStart()
{
	l4d_tank_throw_si = CreateConVar("l4d_tank_throw_si", "30.0", "tank throws special infected [0.0, 100.0]", FCVAR_PLUGIN);
	
	l4d_tank_throw_hunter 	= CreateConVar("l4d_tank_throw_hunter", "10.0", 	"weight of hunter[0.0, 100.0]", FCVAR_PLUGIN);
	l4d_tank_throw_smoker 	= CreateConVar("l4d_tank_throw_smoker", "5.0", 	"[0.0, 10.0]", FCVAR_PLUGIN);
	l4d_tank_throw_boomer 	= CreateConVar("l4d_tank_throw_boomer", "5.0", 	"[0.0, 10.0]", FCVAR_PLUGIN);
	l4d_tank_throw_charger 	= CreateConVar("l4d_tank_throw_charger", "10.0", 	"[0.0, 10.0]", FCVAR_PLUGIN);
	l4d_tank_throw_spitter	= CreateConVar("l4d_tank_throw_spitter", "5.0", 	"[0.0, 10.0]", FCVAR_PLUGIN);
	l4d_tank_throw_jockey	= CreateConVar("l4d_tank_throw_jockey", "10.0",  	"[0.0, 10.0]", FCVAR_PLUGIN);
	l4d_tank_throw_tank	=	  CreateConVar("l4d_tank_throw_tank", "2.0",  	"[0.0, 10.0]", FCVAR_PLUGIN);
	l4d_tank_throw_self	= 	  CreateConVar("l4d_tank_throw_self", "10.0",  	"[0.0, 10.0]", FCVAR_PLUGIN);	
	l4d_tank_throw_tankhealth=CreateConVar("l4d_tank_throw_witch", "10.0",  	"not true", FCVAR_PLUGIN);
	l4d_tank_throw_tankhealth=CreateConVar("l4d_tank_throw_tankhealth", "1000",  	"", FCVAR_PLUGIN);		
	
	HookEvent("round_end", RoundEnd);
	HookEvent("finale_win", RoundEnd);
	HookEvent("mission_lost", RoundEnd);
	HookEvent("map_transition", RoundEnd);
	HookEvent("tank_spawn", RoundStart);
	HookEvent("ability_use", ability_use);
	
	AutoExecConfig(true, "l4d_tankhelper");
	g_iVelocity = FindSendPropOffs("CBasePlayer", "m_vecVelocity[0]");
	
	decl String:GameName[16];
 
	GetGameFolderName(GameName, sizeof(GameName));
	if (StrEqual(GameName, "left4dead2", false))
	{
		L4D2Version=true;
	}	
	else
	{
		L4D2Version=false;
	}

	HookConVarChange(l4d_tank_throw_si, ConVarChange);	
	HookConVarChange(l4d_tank_throw_hunter, ConVarChange);	
	HookConVarChange(l4d_tank_throw_smoker, ConVarChange);	
	HookConVarChange(l4d_tank_throw_boomer, ConVarChange);	
	HookConVarChange(l4d_tank_throw_charger, ConVarChange);	
	HookConVarChange(l4d_tank_throw_spitter, ConVarChange);	
	HookConVarChange(l4d_tank_throw_jockey, ConVarChange);	
	HookConVarChange(l4d_tank_throw_tank, ConVarChange);
	GetConVar();
	gamestart=true;
}
public OnMapStart()
{ 
	if(L4D2Version)
	{ 
		PrecacheParticle("electrical_arc_01_system");
	}
}
public ConVarChange(Handle:convar, const String:oldValue[], const String:newValue[])
{
	GetConVar();

}
GetConVar()
{
	
	throw_all[0]=GetConVarFloat(l4d_tank_throw_hunter );
	throw_all[1]=throw_all[0]+GetConVarFloat(l4d_tank_throw_smoker );
	throw_all[2]=throw_all[1]+GetConVarFloat(l4d_tank_throw_boomer );
	throw_all[3]=throw_all[2]+GetConVarFloat(l4d_tank_throw_tank );	
	throw_all[4]=throw_all[3]+GetConVarFloat(l4d_tank_throw_self );
	throw_all[5]=throw_all[4]+GetConVarFloat(l4d_tank_throw_charger );
	throw_all[6]=throw_all[5]+GetConVarFloat(l4d_tank_throw_spitter );
	throw_all[7]=throw_all[6]+GetConVarFloat(l4d_tank_throw_jockey );
 
}
public Action:RoundStart(Handle:event, const String:name[], bool:dontBroadcast)
{
	gamestart=true;
	tank=0;
}
public Action:RoundEnd(Handle:event, const String:name[], bool:dontBroadcast)
{
	gamestart=false;
}
public Action:ability_use(Handle:event, const String:name[], bool:dontBroadcast)
{
	decl String:s[32];
	GetEventString(event, "ability", s, 32);
	if(StrEqual(s, "ability_throw", true))
	{	
		tank = GetClientOfUserId(GetEventInt(event, "userid"));
	}

}
public OnEntityCreated(entity, const String:classname[])
{
	if(!gamestart)return;
	if(tank>0 && IsValidEdict(entity) && StrEqual(classname, "tank_rock", true) && GetEntProp(entity, Prop_Send, "m_iTeamNum")>=0)
	{
		rock[tank]=entity;
		if( GetRandomFloat(0.0, 100.0)<GetConVarFloat(l4d_tank_throw_si))CreateTimer(0.01, TraceRock, tank, TIMER_REPEAT);
		tank=0;
	}
}
public Action:TraceRock(Handle:timer, any:thetank)
{
	new Float:velocity[3];
	new ent=rock[thetank];
	if(gamestart && IsValidEdict(ent))
	{		
		GetEntDataVector(ent, g_iVelocity, velocity);
		new Float:v=GetVectorLength(velocity)
		if(v>500.0)
		{	
			new Float:pos[3];
			GetEntPropVector(ent, Prop_Send, "m_vecOrigin", pos);
			if(StuckCheck(ent, pos))
			{
				new si=CreateSI(thetank);
				if(si>0)
				{

					RemoveEdict(ent);
					NormalizeVector(velocity, velocity);
					new Float: speed=GetConVarFloat(FindConVar("z_tank_throw_force"));
					ScaleVector(velocity, speed*1.4);
					TeleportEntity(si, pos, NULL_VECTOR, velocity);	
					if(L4D2Version)
					{
						ShowParticle(pos, "electrical_arc_01_system", 3.0);		
					}
				}
				
			}
			return Plugin_Stop;
		}		
		 
	}
	else
	{
		return Plugin_Stop;
	}
	return Plugin_Continue;
}
bool:StuckCheck(ent,  Float:pos[3])
{
	new Float:vAngles[3];
	new Float:vOrigin[3];
	vAngles[2]=1.0;
	GetVectorAngles(vAngles, vAngles);
	new Handle:trace = TR_TraceRayFilterEx(pos, vAngles, MASK_SOLID, RayType_Infinite, TraceRayDontHitSelf,ent);

	if(TR_DidHit(trace))
	{
		TR_GetEndPosition(vOrigin, trace);
	 	new Float:dis=GetVectorDistance(vOrigin, pos);
		if(dis>100.0)return true;
	}
	return false;
}

CreateSI(thetank)
{
	decl bool:IsPalyerSI[MAXPLAYERS+1];
 
	new selected=0;
	for(new i = 1; i <= MaxClients; i++)
	{	
		IsPalyerSI[i]=false;
		if(IsClientInGame(i) && IsPlayerAlive(i))
		{
			if(GetClientTeam(i)==3)
			{
				IsPalyerSI[i]=true;
			}
		}		 
	}
 
	new bool:istank=false;
	new Float:r=GetRandomFloat(0.0, throw_all[4]);
	if(L4D2Version)r=GetRandomFloat(0.0, throw_all[7]);
	
	if(r<throw_all[0])
	{
		CheatCommand(thetank, "z_spawn", "hunter"); 
	}
	else if(r<throw_all[1])
	{
		CheatCommand(thetank, "z_spawn", "smoker"); 
	}
	else if(r<throw_all[2])
	{
		CheatCommand(thetank, "z_spawn", "boomer"); 
	}
	else if(r<throw_all[3])
	{
		CheatCommand(thetank, "z_spawn", "tank"); 
		istank=true;
	}
	else if(r<throw_all[4])
	{
		selected=thetank; 
	}
	else if(r<throw_all[5])
	{
		CheatCommand(thetank, "z_spawn", "charger"); 
	}
	else if(r<throw_all[6])
	{
		CheatCommand(thetank, "z_spawn", "spitter"); 
	}
	else if(r<throw_all[7])
	{
		CheatCommand(thetank, "z_spawn", "jockey"); 
	}
	
	if(selected==0)
	{
		decl andidate[MAXPLAYERS+1];
		new index=0;
		for(new i = 1; i <= MaxClients; i++)
		{	
			if(IsClientInGame(i) && IsPlayerAlive(i) && GetClientTeam(i)==3)
			{
				if(!IsPalyerSI[i])
				{
					selected=i;
					break;
				}
				andidate[index++]=i;
			}		 
		}
		if(selected==0 && index>0)
		{
			selected=andidate[GetRandomInt(0, index-1)];
		}
		
	}
	if(selected>0 && istank)
	{
		SetEntityHealth(selected, GetConVarInt(l4d_tank_throw_tankhealth));
	}
 
 	return selected;
	
}
 
stock CheatCommand(client, String:command[], String:arguments[] = "")
{
	new userFlags = GetUserFlagBits(client);
	SetUserFlagBits(client, ADMFLAG_ROOT);
	new flags = GetCommandFlags(command);
	SetCommandFlags(command, flags & ~FCVAR_CHEAT);
	FakeClientCommand(client, "%s %s", command, arguments);
	SetCommandFlags(command, flags);
	SetUserFlagBits(client, userFlags);
}

public ShowParticle(Float:pos[3], String:particlename[], Float:time)
{
 new particle = CreateEntityByName("info_particle_system");
 if (IsValidEdict(particle))
 {
		TeleportEntity(particle, pos, NULL_VECTOR, NULL_VECTOR);
		DispatchKeyValue(particle, "effect_name", particlename);
		DispatchKeyValue(particle, "targetname", "particle");
		DispatchSpawn(particle);
		ActivateEntity(particle);
		AcceptEntityInput(particle, "start");
		CreateTimer(time, DeleteParticles, particle, TIMER_FLAG_NO_MAPCHANGE);
 } 
}
 
public PrecacheParticle(String:particlename[])
{
 new particle = CreateEntityByName("info_particle_system");
 if (IsValidEdict(particle))
 {
		DispatchKeyValue(particle, "effect_name", particlename);
		DispatchKeyValue(particle, "targetname", "particle");
		DispatchSpawn(particle);
		ActivateEntity(particle);
		AcceptEntityInput(particle, "start");
		CreateTimer(0.01, DeleteParticles, particle, TIMER_FLAG_NO_MAPCHANGE);
 } 
}

public Action:DeleteParticles(Handle:timer, any:particle)
{
	 if (IsValidEntity(particle))
	 {
		 decl String:classname[64];
		 GetEdictClassname(particle, classname, sizeof(classname));
		 if (StrEqual(classname, "info_particle_system", false))
			{
				AcceptEntityInput(particle, "stop");
				AcceptEntityInput(particle, "kill");
				RemoveEdict(particle);
			}
	 }
}
public bool:TraceRayDontHitSelf(entity, mask, any:data)
{
	if(entity == data) 
	{
		return false; 
	}
	return true;
}
 