/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "sm_hsay2",
	author = "Jessecar96",
	description = "hsay without origin",
	version = "1.0",
	url = "jessecar96.net"
}

new g_GameEngine = SOURCE_SDK_UNKNOWN;

public OnPluginStart()
{
	if (g_GameEngine != SOURCE_SDK_DARKMESSIAH)
	{
		RegAdminCmd("sm_hsay2", Command_SmHsay, ADMFLAG_CHAT, "sm_hsay <message> - sends hint message to all players");	
	}
}

public Action:Command_SmHsay(client, args)
{
	if (args < 1)
	{
		ReplyToCommand(client, "[SM] Usage: sm_hsay2 <message>");
		return Plugin_Handled;  
	}
	
	decl String:text[192];
	GetCmdArgString(text, sizeof(text));
 
	decl String:nameBuf[MAX_NAME_LENGTH];
	
	for (new i = 1; i <= MaxClients; i++)
	{
		if (!IsClientInGame(i) || IsFakeClient(i))
		{
			continue;
		}
		FormatActivitySource(client, i, nameBuf, sizeof(nameBuf));
		PrintHintText(i, "%s", text);
	}
	
	LogAction(client, -1, "%L triggered sm_hsay2 (text %s)", client, text);
	
	return Plugin_Handled;	
}