/* Plugin Template generated by Pawn Studio */
/*ChangeLog
*v1.0.0
*  -Inital Relise
* v1.0.1
* -Added chat notofication
* -Fixed Some bugs and Warnings while compile
* v1.0.2
* -Small bugfixes and no more...
* v1.0.3
* -Added CVAR to Enable/Disable plugin
* -Small Bugfixes
* v1.0.4
* -Added restriction CVAR's
* -First public relise
*  */

#include <sourcemod>

new count = 0;
new Handle:CvarEnabled, Handle:CvarRifleman, Handle:CvarAssault, Handle:CvarSupport, Handle:CvarSniper, Handle:CvarMG, Handle:CvarRocket;

 
public Plugin:myinfo = 
{
	name = "Class Restricter",
	author = "Dasister",
	description = "This plugin restricts classes on OrangeBox  and gg_ maps",
	version = "1.0.4",
	url = "http://21games.ru"
}

public OnPluginStart()
{
	CvarEnabled = CreateConVar("cr_enabled", "1", "Sets when plugin enabled <0|1>");
	CvarRifleman = CreateConVar("cr_rifleman", "0", "Restrict Rifleman Class <0|1>");
	CvarAssault = CreateConVar("cr_assault","0","Restricts Assault Class <0|1>");
	CvarSupport = CreateConVar("cr_support","0","Restricts Support Class <0|1>");
	CvarSniper = CreateConVar("cr_sniper", "1","Restricts Sniper Class <0|1>");
	CvarMG = CreateConVar("cr_mg", "1", "Restricts MachineGunner Class <0|1>");
	CvarRocket = CreateConVar("cr_rocket","0","Restricts RocketLauncher Class <0|1>");
	AutoExecConfig(true,"sm_cr","sourcemod")
}

public OnMapStart()
{
	ServerCommand("exec sourcemod/sm_cr.cfg")
	if (GetConVarInt(CvarEnabled))
	{
			LogMessage("[Class Restricter] Plugin sucesfully loaded!")
			new String:mapname[15]
			GetCurrentMap(mapname, 11)
			if (strcmp(mapname, "dod_orange")==0)
			{
				LogMessage("[Class Restricter] It's OrangeBox map! Blocking Classes!")
				if (GetConVarInt(CvarRifleman) == 1)
				{
					ServerCommand("mp_limit_allies_rifleman 0")
					ServerCommand("mp_limit_axis_rifleman 0")
				}
				if (GetConVarInt(CvarAssault) == 1)
				{
					ServerCommand("mp_limit_allies_assault 0")
					ServerCommand("mp_limit_axis_assault 0")	
				}
				if (GetConVarInt(CvarSupport) == 1)
				{
					ServerCommand("mp_limit_allies_support 0")
					ServerCommand("mp_limit_axis_support 0")
				}
				if (GetConVarInt(CvarSniper) == 1)
				{
					ServerCommand("mp_limit_allies_sniper 0")
					ServerCommand("mp_limit_axis_sniper 0")
				}
				if (GetConVarInt(CvarMG) == 1)
				{
					ServerCommand("mp_limit_allies_mg 0")
					ServerCommand("mp_limit_axis_mg 0")
				}
				if (GetConVarInt(CvarRocket) == 1)
				{
					ServerCommand("mp_limit_allies_rocket 0")
					ServerCommand("mp_limit_axis_rocket 0")	
				}
				count = 1
			}
			else
			{
				GetCurrentMap(mapname, 3)
				if (strcmp(mapname, "gg")==0)
				{
					if (GetConVarInt(CvarRifleman) == 1)
					{
						ServerCommand("mp_limit_allies_rifleman 0")
						ServerCommand("mp_limit_axis_rifleman 0")
					}
					if (GetConVarInt(CvarAssault) == 1)
					{
						ServerCommand("mp_limit_allies_assault 0")
						ServerCommand("mp_limit_axis_assault 0")	
					}
					if (GetConVarInt(CvarSupport) == 1)
					{
						ServerCommand("mp_limit_allies_support 0")
						ServerCommand("mp_limit_axis_support 0")
					}
					if (GetConVarInt(CvarSniper) == 1)
					{
						ServerCommand("mp_limit_allies_sniper 0")
						ServerCommand("mp_limit_axis_sniper 0")
					}
					if (GetConVarInt(CvarMG) == 1)
					{
						ServerCommand("mp_limit_allies_mg 0")
						ServerCommand("mp_limit_axis_mg 0")
					}
					if (GetConVarInt(CvarRocket) == 1)
					{
						ServerCommand("mp_limit_allies_rocket 0")
						ServerCommand("mp_limit_axis_rocket 0")	
					}
					count = 2
				}
				else
				{
					LogMessage("[Class Restricter] It's not blocked map! Restoring...")
					ServerCommand("exec server.cfg")
				}
			}

	}
	else
	{
		LogMessage("[Class Restricter] Plugin have been disabled by CVAR's.")
	}
}
public OnClientPutInServer(client)
{
	if (count == 1)
	{
		
		PrintToChat(client, "\x04[Class Restricter] It's OrangeBox map! Some classes blocked")
	}
	else
	{
		if (count == 2)
		{
			PrintToChat(client, "\x04[Class Restricter] It's GunGame map! Some classes blocked")
		}
	}
}