/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "Bonus Money",
	author = "ZERO <ibis>",
	description = "Give players extra money for a kill",
	version = "0.4",
	url = "http://www.IBISGaming.com"
}

new g_MoneyOffset;

public OnPluginStart()
{
	//get offset for money
	g_MoneyOffset = FindSendPropOffs("CCSPlayer", "m_iAccount");
	if (g_MoneyOffset != -1)
	{
		HookEvent("player_death",DeathEvent);
	}
	else
	{
		SetFailState("* FATAL ERROR: Failed to get offset for CCSPlayer::m_iAccount");
	}
	
}

public DeathEvent(Handle:event,const String:name[],bool:dontBroadcast)
{
	new clientid = GetEventInt(event,"attacker");
	new client = GetClientOfUserId(clientid);
	new cash;
	//get current cash and increase the value
	cash=GetEntData(client,g_MoneyOffset,4);
	
	//extra emount to add
	cash+=1000;	
	SetEntData(client, g_MoneyOffset, cash, 4, true);
}