/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#undef REQUIRE_PLUGIN
#include "include\sodsettings.inc"

new g_blockchat[MAXPLAYERS+1];

public Plugin:myinfo = 
{
	name = "SoD Settings Example",
	author = "]SoD[ Frostbyte",
	description = "Example use of sodsettings natives and forwards.",
	version = "1.0",
	url = "www.sonsofdavid.net"
}

public OnPluginStart()
{
	RegConsoleCmd("say", ConCmd_Say);
	RegConsoleCmd("say_team", ConCmd_Say);
}

public Action:ConCmd_Say(client, args)
{
	if(g_blockchat[client] == 1)
		return Plugin_Handled;
	return Plugin_Continue;
}

public OnClientDisconnect(client)
{
	g_blockchat[client] = 0;
}

public OnSettingsChanged(Handle:menu, MenuAction:action, param1, param2)
{
	new String:info[32];
	GetMenuItem(menu, param2, info, sizeof(info));
	if(strcmp(info, "blockchat") == 0)
	{
		g_blockchat[param1] = 1;
		PrintToChat(param1, "\x04[SoD-Settings] Your chat will now be blocked");
	}
	else if(strcmp(info, "unblockchat") == 0)
	{
		g_blockchat[param1] = 0;
		PrintToChat(param1, "\x04[SoD-Settings] You can now chat freely");
	}
}

public OnDisplaySettings(client, Handle:menu)
{
	if(g_blockchat[client] == 0)
		AddMenuItem(menu, "blockchat", "Block chat");
	else
		AddMenuItem(menu, "unblockchat", "Unblock chat");
}
