/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "Strip CVAR Notification",
	author = "Frustian/dcx2 thanks Mr. Zero",
	description = "Strip FCVAR_NOTIFY from a CVAR",
	version = "0.0.3",
	url = "<- URL ->"
}

public OnPluginStart()
{
	RegServerCmd("sm_stripnotify", StripNotification);
	RegServerCmd("sm_addnotify", AddNotification);
	RegServerCmd("sm_scvar", SetCvarWithoutNotification);
}
public Action:StripNotification(args)
{
	new String:cvar[64];
	new Handle:hCvar;
	GetCmdArg(1, cvar, 64);
	hCvar = FindConVar(cvar);
	SetConVarFlags(hCvar, GetConVarFlags(hCvar) & ~FCVAR_NOTIFY);
	return Plugin_Handled;
}
public Action:AddNotification(args)
{
	new String:cvar[64];
	GetCmdArg(1, cvar, 64);
	new Handle:hCvar;
	hCvar = FindConVar(cvar);
	SetConVarFlags(hCvar, GetConVarFlags(hCvar) | FCVAR_NOTIFY);
	return Plugin_Handled;
}
public Action:SetCvarWithoutNotification(args)
{
	new String:cvar[64];
	new String:cvarg[64];
	new Handle:hCvar;
	new flags;
	GetCmdArg(1, cvar, 64);

	if (args >= 2 && GetCmdArg(2, cvarg, sizeof(cvarg)))
	{
		hCvar = FindConVar(cvar);
		flags = GetConVarFlags(hCvar);

		if (flags & FCVAR_NOTIFY) // Remove notify if needed
		{
			SetConVarFlags(hCvar, flags ^ FCVAR_NOTIFY);
		}
		SetConVarString(hCvar, cvarg);
		SetConVarFlags(hCvar, flags); // Restore cvar flags  
	}
	return Plugin_Handled;
}
