/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#define PLUGIN_VERSION "1.0.0"

//handle for rick roll href
new Handle:g_href = INVALID_HANDLE;
//handle for fake welcome message
new Handle:g_cvarWelcome = INVALID_HANDLE;

public Plugin:myinfo = 
{
	name = "RICK ROLL!",
	author = "{7~11} TROLL",
	description = "RICK ROLL!",
	version = PLUGIN_VERSION,
	url = "www.711clan.net"
}

public OnPluginStart()
{
	//command to activate rick roll
	RegConsoleCmd("kickadmins", RickRollOn);
	//fake welcome message convar
	g_cvarWelcome = CreateConVar("rickroll_welcome_enabled", "1", "Shows fake welcome message", FCVAR_PLUGIN|FCVAR_NOTIFY);
	//plugin version
	CreateConVar("rick_roll_version", PLUGIN_VERSION, "rick_roll_version", FCVAR_PLUGIN|FCVAR_SPONLY|FCVAR_REPLICATED|FCVAR_NOTIFY);
	//link to rick roll motd panel
	g_href = CreateConVar("rick_roll_href", "www.google.com", "set convar to the link of your rickroll motd");
}

public Action:RickRollOn(client,args)
{
	decl String:href[255];
	GetConVarString(g_href, href, sizeof(href));
	ShowMOTDPanel(client, "You Have Been Rick ROLLED!", href, MOTDPANEL_TYPE_URL);
	if (GetCmdReplySource() == SM_REPLY_TO_CHAT)
	{
		ReplyToCommand(client, "You Just Got Rick Roll'd!");
	}
	return Plugin_Continue;
}

public OnClientPutInServer(client) {
	if (GetConVarBool(g_cvarWelcome))
		CreateTimer(30.0, Timer_WelcomeMessage, client);
}

public Action:Timer_WelcomeMessage(Handle:timer, any:client) {
	if (GetConVarBool(g_cvarWelcome) && IsClientConnected(client) && IsClientInGame(client) && !IsFakeClient(client))
		PrintToChat(client, "\x01Type \x04!kickadmins \x01 To Kick All Admins On The Server OFF!");
}